name: nivla-ai-main-backend
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      APP_PORT: ${APP_PORT}
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
